services:
  scell.analysis.unite.net:
    image: ghcr.io/dkfz-unite/unite-analysis-scell:latest
    pull_policy: always
    container_name: unite.analysis.scell
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Release
    ports:
      - 127.0.0.1:5302:80
    volumes:
      - unite.analysis.data:/mnt/data:rw

  cxg.viewer.unite.net:
    image: ghcr.io/dkfz-unite/unite-cellxgene:latest
    pull_policy: always
    container_name: unite.analysis.cxg
    restart: no
    ports:
      - 127.0.0.1:54300:80
    volumes:
      - unite.analysis.data:/mnt/data:rw

networks:
  default:
    name: unite
    external: true

volumes:
  unite.analysis.data:
    name: unite.analysis.data
    driver: local
