services:
  analysis-scell:
    extends:
      file: docker-compose.yml
      service: analysis-scell
    volumes:
      - ~/mnt/analysis:/mnt/data:rw

networks:
  default:
    name: unite
    external: true
