services:
  analysis.unite.net:
    extends:
      file: docker-compose.yml
      service: analysis.unite.net
    environment:
      UNITE_ANALYSIS_SHARE_PATH: ~/mnt/analysis
    volumes:
      - ~/mnt/analysis:/mnt/data:rw

networks: 
  default:
    name: unite
    external: true
