version: "3.5"
services:
  analysis.unite.net:
    image: ghcr.io/dkfz-unite/unite-analysis:latest
    container_name: unite.analysis
    restart: unless-stopped
    environment:
      UNITE_API_KEY: ${API_KEY}
      UNITE_ELASTIC_HOST: http://es.unite.net:9200
      UNITE_ELASTIC_USER: ${ELASTIC_USER}
      UNITE_ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      UNITE_SQL_HOST: pgsql.unite.net
      UNITE_SQL_PORT: 5432
      UNITE_SQL_USER: ${SQL_USER}
      UNITE_SQL_PASSWORD: ${SQL_PASSWORD}
      UNITE_ANALYSIS_DATA_PATH: /mnt/data
      UNITE_ANALYSIS_DESEQ2_URL: http://localhost:5300
      ASPNETCORE_ENVIRONMENT: Release
    ports: 
      - 127.0.0.1:5004:80
    volumes:
      - unite.analysis.data:/mnt/data:rw

networks: 
  default:
    name: unite
    external: true

volumes:
  unite.analysis.data:
    name: unite.analysis.data
    driver: local
