services:
  mysql.unite.net:
    image: mysql:5.6
    platform: linux/amd64
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
    volumes:
     - mysql.data:/var/lib/mysql:rw
     - ./cache:/home/mysql/cache:rw
    ports:
      - 127.0.0.1:3306:3306

networks: 
  default:
    name: unite
    external: true

volumes:
  mysql.data:
    name: mysql.data
    driver: local
