version: '3.5'
services:
  mysql.unite.net:
    image: mysql:5.6
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
    volumes:
     - ./cache:/home/mysql/cache:rw
    ports:
      - 127.0.0.1:3306:3306

networks: 
  default:
    external: 
      name: unite
