services:
  traefik:
    extends:
      file: docker-compose.yml
      service: traefik
  
  portal:
    extends:
      file: docker-compose.yml
      service: portal
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    image: unite.portal
    
networks: 
  default:
    name: unite
    external: true
