version: '3.5'
services:
  web.unite:
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    image: unite.web
    container_name: unite.web
    restart: unless-stopped
    environment: 
      ASPNETCORE_ENVIRONMENT: Release
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_URLS: https://+:443;http://+:80
      # ASPNETCORE_Kestrel__Certificates__Default__Path: /https/10.128.130.194.crt
      # ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /https/10.128.130.194.key
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost+4.pem
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /https/localhost+4-key.pem
      UNITE_COMPOSER_HOST: http://composer.unite
    volumes: 
      - "../../ssl:/https:ro"
    ports: 
      - "80:80"
      - "443:443"
    
networks: 
  default:
    external:
      name: unite
      
    
    
