version: '3.5'
services:
  web.unite:
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    image: unite.web
    container_name: unite.web
    environment: 
      ASPNETCORE_ENVIRONMENT: Release
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${SSL_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/unite.pfx
      UNITE_COMPOSER_HOST: http://composer.unite
    volumes: 
      - "../../ssl:/https:ro"
    ports: 
      - "80:80"
      - "443:443"
    
networks: 
  default:
    external:
      name: unite
      
    
    