services:
  traefik:
    image: traefik:v3.2
    container_name: unite.traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8084:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portal:
    image: ghcr.io/dkfz-unite/unite:latest
    pull_policy: always
    container_name: unite.portal
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portal.rule=PathPrefix(`/`)"
    
networks: 
  default:
    name: unite
    external: true
