version: '3.5'
services:
  web.unite:
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    image: unite.web
    container_name: unite.web
    restart: unless-stopped
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.crt
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /https/localhost.key
      UNITE_COMPOSER_HOST: http://composer.unite
    volumes: 
      - "../../ssl:/https:ro"
    ports: 
      - "80:80"
      - "443:443"

networks: 
  default:
    external: 
      name: unite
      
    
    
