services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    volumes:
      - mongo.data:/data/db:rw
      - mongo.config:/data/configdb:rw
    ports:
      - 127.0.0.1:27017:27017

networks: 
  default:
    name: unite
    external: true

volumes:
  mongo.data:
    name: mongo.data
    driver: local
  mongo.config:
    name: mongo.config
    driver: local
