version: '3.5'
services:
  mgmt.sql.unite.net:
    image: adminer
    container_name: sql.mgmt
    restart: unless-stopped
    ports: 
      - 8081:8080

networks: 
  default:
    external: 
      name: unite