version: "3.5"
services:
  mgmt.pgsql.unite.net:
    image: adminer
    container_name: pgsql.mgmt
    restart: unless-stopped
    ports: 
      - 8081:8080

networks: 
  default:
    name: unite
    external: true
