services:
  rna-de.analysis.unite.net:
    image: ghcr.io/dkfz-unite/unite-analysis-rna-de:latest
    pull_policy: always
    container_name: unite.analysis.rna-de
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Release
    ports:
      - 127.0.0.1:5300:80
    volumes:
      - unite.analysis.data:/mnt/data:rw

networks:
  default:
    name: unite
    external: true

volumes:
  unite.analysis.data:
    name: unite.analysis.data
    driver: local
