version: "3.5"
services:
  deseq2.analysis.unite.net:
    extends:
      file: docker-compose.yml
      service: deseq2.analysis.unite.net
    build:
      context: ./src
      dockerfile: ./Dockerfile
      args:
        USER: ${GITHUB_USER}
        TOKEN: ${GITHUB_TOKEN}
    image: unite.analysis.deseq2
    volumes:
      - ~/mnt/analysis:/mnt/data:rw

networks:
  default:
    name: unite
    external: true
