services:
  rnasc-dc.analysis.unite.net:
    extends:
      file: docker-compose.yml
      service: rnasc-dc.analysis.unite.net
    build:
      context: ./src
      dockerfile: ./Dockerfile
    image: unite.analysis.rnasc-dc
    volumes:
      - ~/mnt/analysis:/mnt/data:rw
      - ./cache:/root/.celltypist/data/models:rw
    
  cxg.viewer.unite.net:
    extends:
      file: docker-compose.yml
      service: cxg.viewer.unite.net
    volumes:
      - ~/mnt/analysis:/mnt/data:rw

networks:
  default:
    name: unite
    external: true
