services:
  kmeier.analysis.unite.net:
    extends:
      file: docker-compose.yml
      service: kmeier.analysis.unite.net
    build:
      context: ./src
      dockerfile: ./Dockerfile
    image: unite.analysis.kmeier
    volumes:
      - unite.analysis.data:/mnt/data:rw

networks:
  default:
    name: unite
    external: true

volumes:
  unite.analysis.data:
    name: unite.analysis.data
    driver: local
