services:
  analysis-kmeier:
    extends:
      file: docker-compose.yml
      service: analysis-kmeier
    build:
      context: ./src
      dockerfile: ./Dockerfile
    image: unite.analysis.kmeier
    volumes:
      - ~/mnt/analysis:/mnt/data:rw

networks:
  default:
    name: unite
    external: true
