services:
  specimens-feed:
    extends:
      file: docker-compose.yml
      service: specimens-feed
    build: 
      context: ./src
      dockerfile: ./Dockerfile
      args: 
        USER: ${GITHUB_USER}
        TOKEN: ${GITHUB_TOKEN}
    image: unite.specimens.feed

networks: 
  default:
    name: unite
    external: true
