services:
  images-feed:
    image: ghcr.io/dkfz-unite/unite-images-feed:latest
    pull_policy: always
    container_name: unite.images.feed
    restart: unless-stopped
    environment:
      UNITE_API_KEY: ${API_KEY}
      UNITE_ELASTIC_HOST: http://es:9200
      UNITE_ELASTIC_USER: ${ELASTIC_USER}
      UNITE_ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      UNITE_SQL_HOST: pgsql
      UNITE_SQL_PORT: 5432
      UNITE_SQL_USER: ${SQL_USER}
      UNITE_SQL_PASSWORD: ${SQL_PASSWORD}
      UNITE_MONGO_HOST: mongo
      UNITE_MONGO_PORT: 27017
      UNITE_MONGO_USER: ${MONGO_USER}
      UNITE_MONGO_PASSWORD: ${MONGO_PASSWORD}
      UNITE_INDEXING_BUCKET_SIZE: 10
      ASPNETCORE_ENVIRONMENT: Release
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.images-feed-replaceregex.replacepathregex.regex=^/api/images-feed/(.*)"
      - "traefik.http.middlewares.images-feed-replaceregex.replacepathregex.replacement=/api/$${1}"
      - "traefik.http.routers.images-feed.rule=Host(`localhost`) && PathPrefix(`/api/images-feed`)"
      - "traefik.http.routers.images-feed.middlewares=images-feed-replaceregex"
    ports: 
      - 127.0.0.1:5102:80

networks: 
  default:
    name: unite
    external: true
