services:
  images-feed:
    extends:
      file: docker-compose.yml
      service: images-feed
    build: 
      context: ./src
      dockerfile: ./Dockerfile
      args: 
        USER: ${GITHUB_USER}
        TOKEN: ${GITHUB_TOKEN}
    image: unite.images.feed

networks: 
  default:
    name: unite
    external: true
