version: "3.5"
services:
  migrations.identity.unite.net:
    image: ghcr.io/dkfz-unite/unite-identity-data-migrations:latest
    container_name: unite.identity.migrations
    environment:
      UNITE_SQL_HOST: pgsql.unite.net
      UNITE_SQL_PORT: 5432
      UNITE_SQL_USER: ${SQL_USER}
      UNITE_SQL_PASSWORD: ${SQL_PASSWORD}
      ASPNETCORE_ENVIRONMENT: Release

networks: 
  default:
    name: unite
    external: true
