services:
  identity-migrations:
    image: ghcr.io/dkfz-unite/unite-identity-data-migrations:latest
    pull_policy: always
    container_name: unite.identity.migrations
    environment:
      UNITE_SQL_HOST: pgsql
      UNITE_SQL_PORT: 5432
      UNITE_SQL_USER: ${SQL_USER}
      UNITE_SQL_PASSWORD: ${SQL_PASSWORD}
      ASPNETCORE_ENVIRONMENT: Release

networks: 
  default:
    name: unite
    external: true
