version: "3.5"
services:
  composer.unite.net:
    build: 
      context: ./src
      dockerfile: ./Dockerfile
      args: 
        USER: ${GITHUB_USER}
        TOKEN: ${GITHUB_TOKEN}
    image: unite.composer
    container_name: unite.composer
    restart: unless-stopped
    environment:
      UNITE_API_KEY: ${API_KEY}
      UNITE_ELASTIC_HOST: http://es.unite.net:9200
      UNITE_ELASTIC_USER: ${ELASTIC_USER}
      UNITE_ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      UNITE_SQL_HOST: pgsql.unite.net
      UNITE_SQL_PORT: 5432
      UNITE_SQL_USER: ${SQL_USER}
      UNITE_SQL_PASSWORD: ${SQL_PASSWORD}
      UNITE_ENSEMBL_HOST: http://data.ensembl.unite.net
      ASPNETCORE_ENVIRONMENT: Release
    ports: 
      - 127.0.0.1:5002:80
    volumes: 
      - "./data:/app/data:rw"

networks: 
  default:
    name: unite
    external: true
