services:
  composer:
    image: ghcr.io/dkfz-unite/unite-composer:latest
    pull_policy: always
    container_name: unite.composer
    restart: unless-stopped
    environment:
      UNITE_API_KEY: ${API_KEY}
      UNITE_ELASTIC_HOST: http://es:9200
      UNITE_ELASTIC_USER: ${ELASTIC_USER}
      UNITE_ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      UNITE_SQL_HOST: pgsql
      UNITE_SQL_PORT: 5432
      UNITE_SQL_USER: ${SQL_USER}
      UNITE_SQL_PASSWORD: ${SQL_PASSWORD}
      UNITE_ENSEMBL_HOST: http://ensembl-data
      ASPNETCORE_ENVIRONMENT: Release
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.composer-replaceregex.replacepathregex.regex=^/api/composer/(.*)"
      - "traefik.http.middlewares.composer-replaceregex.replacepathregex.replacement=/api/$${1}"
      - "traefik.http.routers.composer.rule=Host(`localhost`) && PathPrefix(`/api/composer`)"
      - "traefik.http.routers.composer.middlewares=composer-replaceregex"
    ports: 
      - 127.0.0.1:5002:80

networks: 
  default:
    name: unite
    external: true
