services:
  composer:
    extends:
      file: docker-compose.yml
      service: composer
    build: 
      context: ./src
      dockerfile: ./Dockerfile
      args: 
        USER: ${GITHUB_USER}
        TOKEN: ${GITHUB_TOKEN}
    image: unite.composer

networks: 
  default:
    name: unite
    external: true
