services:
  identity.unite.net:
    image: ghcr.io/dkfz-unite/unite-identity:latest
    pull_policy: always
    container_name: unite.identity
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Release
      UNITE_SQL_HOST: pgsql.unite.net
      UNITE_SQL_PORT: 5432
      UNITE_SQL_USER: ${SQL_USER}
      UNITE_SQL_PASSWORD: ${SQL_PASSWORD}
      UNITE_API_KEY: ${API_KEY}
      UNITE_ADMIN_USER: ${ADMIN_USER}
      UNITE_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      UNITE_DEFAULT_LABEL: "UNITE"
      UNITE_DEFAULT_PRIORITY: 1
    ports: 
      - 127.0.0.1:5000:80

networks: 
  default:
    name: unite
    external: true
