version: "3"
services:
  process.vcfstandardization.unite:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: unite.vcfstandardization.process
    container_name: unite.vcfstandardization.process
    environment:
      ASPNETCORE_ENVIRONMENT: Release
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Password: 100500
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/unite.pfx

    volumes:
      - ${HOSTPATH}:/mnt/hipo_057
    ports:
      - 127.0.0.1:80:80
    cap_add:
      - SYS_ADMIN
    security_opt:
      - "apparmor:unconfined"
networks:
  default:
    external:
      name: unite
