version: "3"
services:
  mutations.source.otp.unite:
    build:
      context: ./src
      dockerfile: ./DockerfileLocalDevelopment
    image: unite.mutations.source.otp
    container_name: unite.mutations.source.otp
    environment:
      ASPNETCORE_ENVIRONMENT: Release
      UNITE_ELASTIC_HOST: “http://es.unite:9200”
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Password: 100500
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/unite.pfx
      ODCF_SERVER: odcf-worker01
      ODCF_USER: m309e
      OTP_FEEDER_URL: http://mutations.feed.unite/api/mutations
      OTP_MONGOHOST: mongo
      OTP_WALKDIRS: '["exon_sequencing/view-by-pid", "rna_sequencing/view-by-pid", "whole_genome_sequencing/view-by-pid"]'
      ODCF_REMOTE_DIR: ${ODCF_REMOTE_DIR}
      ODCF_FILE_EXTENSION: ${ODCF_FILE_EXTENSION}      
    volumes:
      - /etc/ssl/certs/:/etc/ssl/certs/
      - /home/otp:/opt/vep/.vep
      - /home/right/WindowsDocuments/eclipse-workspace/UNITEotp/src/UNITEotp:/usr/local/lib/python3.6/dist-packages/UNITEotp
      - /home/right/WindowsDocuments/eclipse-workspace/UNITEmsc/src/UNITEmsc:/usr/local/lib/python3.6/dist-packages/UNITEmsc
    ports:
      - 127.0.0.1:5000:80
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    security_opt:
      - "apparmor:unconfined"
networks:
  default:
    external:
      name: unite
