version: "3"
services:
  mutations.source.otp.unite:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    image: unite.mutations.source.otp
    container_name: unite.mutations.source.otp
    environment:
      UNITE_ELASTIC_HOST: “http://es.unite:9200”
      ODCF_SERVER: odcf-worker01
      ODCF_USER: m309e
      OTP_FEEDER_URL: http://mutations.feed.unite/api/mutations
      OTP_MONGOHOST: mongo
      OTP_WALKDIRS: '["exon_sequencing/view-by-pid", "rna_sequencing/view-by-pid", "whole_genome_sequencing/view-by-pid"]'
      ODCF_REMOTE_DIR: ${ODCF_REMOTE_DIR}
      ODCF_FILE_EXTENSION: ${ODCF_FILE_EXTENSION}      
    volumes:
      - /etc/ssl/certs/:/etc/ssl/certs/
      - /home/otp:/opt/vep/.vep
    ports:
      - 127.0.0.1:5000:80
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    security_opt:
      - "apparmor:unconfined"
networks:
  default:
    external:
      name: unite
