services:
  view.scell.analysis.unite.net:
    extends:
      file: docker-compose.yml
      service: view.scell.analysis.unite.net
    volumes:
      - ~/mnt/analysis:/data:rw

networks:
  default:
    name: unite
    external: true
