services:
  feed.specimens.unite.net:
    image: ghcr.io/dkfz-unite/unite-specimens-feed:latest
    pull_policy: always
    container_name: unite.specimens.feed
    restart: unless-stopped
    environment:
      UNITE_API_KEY: ${API_KEY}
      UNITE_ELASTIC_HOST: http://es.unite.net:9200
      UNITE_ELASTIC_USER: ${ELASTIC_USER}
      UNITE_ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      UNITE_SQL_HOST: pgsql.unite.net
      UNITE_SQL_PORT: 5432
      UNITE_SQL_USER: ${SQL_USER}
      UNITE_SQL_PASSWORD: ${SQL_PASSWORD}
      UNITE_MONGO_HOST: mongo.unite.net
      UNITE_MONGO_PORT: 27017
      UNITE_MONGO_USER: ${MONGO_USER}
      UNITE_MONGO_PASSWORD: ${MONGO_PASSWORD}
      UNITE_INDEXING_BUCKET_SIZE: 10
      ASPNETCORE_ENVIRONMENT: Release
    ports: 
      - 127.0.0.1:5104:80

networks: 
  default:
    name: unite
    external: true
