version: "3.5"
services:
  feed.genome.unite.net:
    extends:
      file: docker-compose.yml
      service: feed.genome.unite.net
    build: 
      context: ./src
      dockerfile: ./Dockerfile
      args: 
        USER: ${GITHUB_USER}
        TOKEN: ${GITHUB_TOKEN}
    image: unite.genome.feed

networks: 
  default:
    name: unite
    external: true
