services:
  ensembl-vep:
    image: ghcr.io/dkfz-unite/unite-ensembl-vep:latest
    pull_policy: always
    container_name: unite.ensembl.vep
    restart: unless-stopped
    environment: 
      ASPNETCORE_ENVIRONMENT: Release
    ports: 
      - 127.0.0.1:5202:80
    volumes: 
      - "./data:/cache:rw"

networks: 
  default:
    name: unite
    external: true
