services:
  meth.analysis.unite.net:
    extends:
      file: docker-compose.yml
      service: meth.analysis.unite.net
    build:
      context: ./src
      dockerfile: ./Dockerfile
    image: unite.analysis.meth
    volumes:
      - ~/mnt/analysis:/mnt/data:rw

networks:
  default:
    name: unite
    external: true