version: "3.5"
services:
  data.ensembl.unite.net:
    image: ghcr.io/dkfz-unite/unite-ensembl-data:latest
    container_name: unite.ensembl.data
    restart: unless-stopped
    environment: 
      ENSEMBL_SQL_HOST: mysql.unite.net
      ENSEMBL_SQL_PORT: 3306
      ENSEMBL_SQL_USER: root
      ENSEMBL_SQL_PASSWORD: ${SQL_PASSWORD}
      ENSEMBL_RELEASE: "109_37"
      ASPNETCORE_ENVIRONMENT: Release
    ports: 
      - 127.0.0.1:5200:80

networks: 
  default:
    name: unite
    external: true
