services:
  ensembl-data:
    extends: 
      file: docker-compose.yml
      service: ensembl-data
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    image: unite.ensembl.data

networks: 
  default:
    name: unite
    external: true
